#informal testing
indata <- readRDS("~/Dropbox/grad_school/johnson_lab/20180725_latent_capetown_2018/latent_capetown_2018_SCE.rds")
indata_SCE <- as(indata, "SingleCellExperiment")
indata_SE <- as(indata, "SummarizedExperiment")
indata_df <- data.frame(assay(indata, "tpmlog"))
indata_mat <- assay(indata, "tpmlog")

test_GSVA01 <- runTBsigProfiler(input=indata, useAssay = "tpmlog", algorithm = "GSVA")
test_GSVA02 <- runTBsigProfiler(input=indata, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "matrix")
test_GSVA03 <- runTBsigProfiler(input=indata, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "data.frame")
test_GSVA04 <- runTBsigProfiler(input=indata_SCE, useAssay = "tpmlog", algorithm = "GSVA")
test_GSVA05 <- runTBsigProfiler(input=indata_SCE, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "matrix")
test_GSVA06 <- runTBsigProfiler(input=indata_SCE, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "data.frame")
test_GSVA07 <- runTBsigProfiler(input=indata_SE, useAssay = "tpmlog", algorithm = "GSVA")
test_GSVA08 <- runTBsigProfiler(input=indata_SE, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "matrix")
test_GSVA09 <- runTBsigProfiler(input=indata_SE, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "data.frame")
test_GSVA10 <- runTBsigProfiler(input=indata_df, useAssay = "tpmlog", algorithm = "GSVA")
test_GSVA11 <- runTBsigProfiler(input=indata_df, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "matrix")
test_GSVA12 <- runTBsigProfiler(input=indata_df, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "data.frame")
test_GSVA13 <- runTBsigProfiler(input=indata_mat, useAssay = "tpmlog", algorithm = "GSVA")
test_GSVA14 <- runTBsigProfiler(input=indata_mat, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "matrix")
test_GSVA15 <- runTBsigProfiler(input=indata_mat, useAssay = "tpmlog", algorithm = "GSVA", outputFormat = "data.frame")

test2 <- runTBsigProfiler(input=indata, useAssay = "tpmlog", algorithm = "ssGSEA")
